version: '3.9'

services:

  web:
    build: .
    ports:
      - "4200:80"
  dev:
    build:
      context: .
      dockerfile: Dockerfile.serve
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
      - "3001:3001"
