backend:
  name: github
  repo: DefGuard/defguard.github.io 
  branch: master
  api_root: https://api.github.com 
  site_domain: defguard.net
  base_url: https://decap-dfg.teonite.net
  auth_endpoint: auth
  cms_label_prefix: decap/

publish_mode: editorial_workflow
local_backend: true
media_folder: "static/images/decap"
public_folder: "/images/decap" 
collections:
  - name: meta
    label: Meta config
    files:
      - name: meta
        label: Meta config
        file: "data/meta.yml"
        fields:
          - name: title
            label: Website title
            widget: string
          - name: description
            label: Description
            widget: string
          - name: openGraph
            label: Open Graph
            widget: object
            summary: Open Graph config
            required: false
            fields:
              - name: title
                label: Title
                widget: string
                required: false
              - name: url
                label: URL
                widget: string
                required: false
              - name: description
                label: Description
                widget: string
                required: false
              - name: image
                label: Image
                required: false
                widget: image
          - name: twitter
            label: Twitter
            widget: object
            summary: Twitter card config
            required: false
            fields:
              - name: card
                label: Card
                widget: select
                default: summary
                required: false
                options:
                  - summary
                  - summary_large_image
                  - app
                  - player
              - name: attribution
                label: Attribution
                widget: object
                required: false
                fields:
                  - name: site
                    label: Site
                    widget: string
                    required: false
                  - name: creator
                    label: Creator
                    widget: string
                    required: false
  - name: "landing"
    label: "Landing page configuration"
    files:
      - name: "LandingData" 
        label: "Config"
        file: "data/landing.yml"
        fields:
          - label: Header
            name: header
            widget: object
            summary: '{{fields.title}}'
            fields:
              - {label: Title, name: title, widget: markdown}
              - {label: Sub content, name: content, widget: markdown}
              - {label: Image, name: image, widget: image}
          - label: Features
            name: features
            widget: list
            summary: "{{fields.name}}"
            fields:
              - name: icon
                label: Icon
                widget: select
                default: shield
                options: 
                  - branching
                  - shield
                  - wallet
                  - hardkey
                  - openid
                  - piechart
                  - settings
                  - user
                  - webhook
                  - yubikey
                  - googleAuth
              - {label: Name, name: name, widget: string}
              - {label: Section ID, name: id, widget: string, required: false}
              - {label: Description, name: description, widget: markdown}
              - {label: Image, name: image, widget: image} 
  - name: socials
    label: "Socials config"
    files:
      - name: socialsData
        label: Links config
        file: "data/socials.yml"
        fields:
          - label: Links
            name: links
            widget: list
            summary: '{{fields.name}}'
            fields:  
              - {label: Icon, name: icon, widget: image}
              - {label: Name, name: name, widget: string}
              - {label: Link, name: link, widget: string}      
  - name: "navigation"
    label: "Navigation config"
    files:
      - name: "navigationData"
        label: "Navigation config"
        file: "data/navigation.yml"
        fields:
          - label: Links
            name: links
            widget: list
            summary: '{{fields.text}}'
            fields:
              - {label: Text, name: text, widget: string}
              - {label: Link, name: link, widget: string}
              - {label: Target, name: target, widget: select, options: ['blank', 'self'], default: 'self'}
  - name: "footer"
    label: "Footer config"
    files:
      - name: "footerData"
        label: "Footer config"
        file: "data/footer.yml"
        fields:
          - name: columns
            label: Columns
            widget: list
            summary: '{{fields.title}}'
            fields:
              - name: title
                label: Title
                widget: string
              - name: links
                label: Links
                widget: list
                summary: '{{fields.text}}'
                fields:
                  - name: text
                    label: Text
                    widget: string
                  - name: link
                    label: Link
                    widget: string
                  - name: target
                    label: Target
                    widget: select
                    options: ['blank', 'self']
                    default: 'blank'
          - name: copyright
            label: Copyright
            widget: markdown
