backend:
  name: github
  repo: DefGuard/defguard.github.io 
  branch: master
  api_root: https://api.github.com 
  site_domain: defguard.github.io
  base_url: https://decap-dfg.teonite.net
  auth_endpoint: auth
  cms_label_prefix: decap/

publish_mode: editorial_workflow
local_backend: true
media_folder: "static/images/decap"
public_folder: "/images/decap" 
collections:
  - name: "landing"
    label: "Landing"
    files:
      - name: "LandingData" 
        label: "Landing page config"
        file: "data/landing.yml"
        fields:
          - label: Header
            name: header
            widget: object
            fields:
              - {label: Title, name: title, widget: markdown}
              - {label: Sub content, name: content, widget: markdown}
          - label: Features
            name: features
            widget: list
            fields:
              - {label: Icon, name: icon, widget: select, options: ['branching', 'shield', 'wallet'], default: 'shield'}
              - {label: Name, name: name, widget: text}
              - {label: Description, name: description, widget: markdown}
              - {label: Image, name: image, widget: image} 
  - name: socials
    label: "Socials config"
    files:
      - name: socialsData
        label: Links config
        file: "data/socials.yml"
        fields:
          - label: Links
            name: links
            widget: list
            fields:  
              - {label: Icon, name: icon, widget: image}
              - {label: Name, name: name, widget: string}
              - {label: Link, name: link, widget: string}      
  - name: "navigation"
    label: "Navigation config"
    files:
      - name: "navigationData"
        label: "Navigation config"
        file: "data/navigation.yml"
        fields:
          - label: Links
            name: links
            widget: list
            fields:
              - {label: Text, name: text, widget: text}
              - {label: Link, name: link, widget: text}
              - {label: Target, name: target, widget: select, options: ['blank', 'self'], default: 'self'}
